import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Intro from "../components/homepage/intro/intro";
import Hyper from "../components/homepage/hyper/hyper";
import Features from "../components/homepage/features/features";
import Separator from "../components/homepage/separator/separator";
import Cards from "../components/homepage/cards/cards";
import Nodos from "../components/homepage/nodos/nodos";
import About from "../components/homepage/about/about";
import Footer from "../components/footer/footer";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Block2Trace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Intro />
        <Hyper />
        <Features />
        <Separator />
        <Cards />
        <Nodos />
        <About />
      </main>

      <Footer/>

    </div>
  )
}
